---
language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
before_install:
  - gem update --system
  - gem install bundler
cache: bundler
env:
  - EMAIL="<EMAIL>" PASSWORD="<PASSWORD>" INSTANCE_ZUID="1-abc-def" MODEL_ZUID="6-d08392dbc9-9gl4bk"
