---
language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
before_install: gem install bundler
cache: bundler
sudo: false
fast_finish: true
notifications:
  email:
    on_success: always
    on_failure: always
