name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.4', '2.5', '2.6', '2.7' ]
    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install rubygems
      run: |
        gem update --system --no-document

    - name: Install bundler
      run: |
        gem install bundler --no-document

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run Tests
      env:
        EMAIL: email
        PASSWORD: password
        INSTANCE_ZUID: ${{ secrets.INSTANCE_ZUID }}
        MODEL_ZUID: ${{ secrets.MODEL_ZUID }}
      run: |
        bundle exec rake
